### ISSUE TITLE
Cloud Vision Api? 

### ISSUE THREAD

**Issue by max-xoo** [aw1875/puppeteer-hcaptcha#10]
Hello, after walking your package I realized that Cloud Vision pi had to see a way to pay, it's a paid service? Then if possible, you have a method to do all this for free that would be nice.

**Comment by aw1875** [comment]
@max-xoo You can sign up for Google Vision for free and it comes with a $300 credit to start. However, someone has created a pull request to add the option to randomly solve the pictures without Google Vision (so it wouldn't need it) but it is much slower. Need to figure out what the issues are before I accept the merge request.

**Comment by max-xoo** [comment]
Hello I have ! Indeed the person who did that, I saw what she did, unfortunately my captcha is in a frame (discord.com/register after being entered), so it doesn't work! Neither your code nor that of the other person who modified yours

**Comment by aw1875** [comment]
Usually all hcaptcha challenges are within an iframe. For discord you may just have to tweak some code for it to work.

**Comment by max-xoo** [comment]
Ok thanks !
