### ISSUE TITLE
About new update

### ISSUE THREAD

**Issue by klotein** [aw1875/puppeteer-hcaptcha#12]
Hi, im here again. Your project is going well, good lucks. But im again getting similar error like before new update about for Cloudflare Hcaptcha pages.
`TypeError: Cannot read property 'type' of undefined` error here. Thanks.

**Comment by aw1875** [comment]
Do you mind giving a little more context to the error? Maybe a full stack trace if possible. Also, is it the same website as your last issue?

**Comment by klotein** [comment]
`node:7996) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'type' of undefined
    at tryToSolve (C:\Users\ops\node_modules\puppeteer-hcaptcha\hcaptcha.js:76:18)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async solveCaptcha (C:\Users\ops\node_modules\puppeteer-hcaptcha\hcaptcha.js:215:22)      
    at async hcaptchaToken (C:\Users\ops\node_modules\puppeteer-hcaptcha\hcaptcha.js:296:10)     
    at async C:\Users\ops\Desktop\den\solve.js:21:17
(Use `node --trace-warnings ...` to show where the warning was created)
(node:7996) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7996) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.` Yes, same websites.

**Comment by aw1875** [comment]
Thank you. I just checked the request and looks like one of the checks I had added for HSJ requests doesn't exist with cloudflare sites so I will fix that and push a fix in a few.

**Comment by aw1875** [comment]
New version should be live with the fix, let me know if there are any issues by reopening this issue!
