### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by iban79** [aw1875/puppeteer-hcaptcha#14]
Could you help me? when I start .js I get this error:

D: \ Downloads \ puppeteer-hcaptcha-master \ puppeteer-hcaptcha-master> node t.js
(node: 8328) UnhandledPromiseRejectionWarning: Error: Evaluation failed: Error: ENOENT: no such file or directory, open 'C: \ UsersAdministradorDownloadsMy First Project-f2a901bcd6f9.json'
    at ExecutionContext._evaluateInternal (D: \ Downloads \ puppeteer-hcaptcha-master \ puppeteer-hcaptcha-master \ node_modules \ puppeteer \ lib \ cjs \ puppeteer \ common \ ExecutionContext.js: 218: 19)
    at processTicksAndRejections (internal / process / task_queues.js: 93: 5)
    at async ExecutionContext.evaluate (D: \ Downloads \ puppeteer-hcaptcha-master \ puppeteer-hcaptcha-master \ node_modules \ puppeteer \ lib \ cjs \ puppeteer \ common \ ExecutionContext.js: 107: 16)
    at async hcaptcha (D: \ Downloads \ puppeteer-hcaptcha-master \ puppeteer-hcaptcha-master \ node_modules \ puppeteer-hcaptcha \ hcaptcha.js: 241: 17)
    at async D: \ Downloads \ puppeteer-hcaptcha-master \ puppeteer-hcaptcha-master \ t.js: 48: 5
(Use `node --trace-warnings ...` to show where the warning was created)
(node: 8328) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch (). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections = strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node: 8328) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

--------------------------------------------------  My code is this  ---------------------------------------

const pluginStealth = require('puppeteer-extra-plugin-stealth')
const vision = require("@google-cloud/vision");

// Require our hcaptcha method
const { hcaptcha } = require('puppeteer-hcaptcha');

// Instantiate a new Google Vision Client
// This is important so make sure keyFilename points to your credentials
// Our solver method will be using this to speed up the process
const client = new vision.ImageAnnotatorClient({
  keyFilename: "C:\Users\Administrador\Downloads\My First Project-f2a901bcd6f9.json",
});

// Tell puppeteer to use puppeteer stealth
puppeteer.use(pluginStealth());

(async () => {
    // Instantiate a new browser object
    // Ignore errors associated to https
    // Can be headless but for example sake we want to show the browser
    // Set your desired arguments for your puppeteer browser
    const browser = await puppeteer.launch({
        ignoreHTTPSErrors: true,
        headless: false,
        args: [
          `--window-size=600,1000`,
          "--window-position=000,000",
          "--disable-dev-shm-usage",
          "--no-sandbox",
          '--user-data-dir="/tmp/chromium"',
          "--disable-web-security",
          "--disable-features=site-per-process"
        ],
      });

    // Get browser pages
    const [page] = await browser.pages();

    // Send page to your url
    await page.goto('http://captcha.cryptowin.io:3000/')

    // Remove the page's default timeout function
    await page.setDefaultNavigationTimeout(0);

    // Call hcaptcha method passing in our page and google vision client
    await hcaptcha(page, client);

    // Your page is ready to submit. Captcha solving should be the last function on your page so we don't have to worry about the response token expiring.
})();

**Comment by aw1875** [comment]
`(node: 8328) UnhandledPromiseRejectionWarning: Error: Evaluation failed: Error: ENOENT: no such file or directory, open 'C: \ UsersAdministradorDownloadsMy First Project-f2a901bcd6f9.json'` in the stack trace means that there is an issue with your google vision auth file:

```javascript
const client = new vision.ImageAnnotatorClient({
    keyFilename: "C:\Users\Administrador\Downloads\My First Project-f2a901bcd6f9.json",
});
```

The way you point to your file isn't correct. It should be:

```javascript
const client = new vision.ImageAnnotatorClient({
    keyFilename: "C:\\Users\\Administrador\\Downloads\\My First Project-f2a901bcd6f9.json",
});
```

An easier way to do this would be just to copy the json file to your project directory at the same level as your code and just make it:

```javascript
const client = new vision.ImageAnnotatorClient({
    keyFilename: "./My First Project-f2a901bcd6f9.json",
});
```

**Comment by iban79** [comment]
Thank you.
