### ISSUE TITLE
Add status and solve times

### ISSUE THREAD

**Issue by durch2** [aw1875/puppeteer-hcaptcha#15]
Would be helpful if you included status, solve time in the readme :)

**Comment by aw1875** [comment]
Sorry a little confused what you mean by status? In terms of solve time there are a couple very easy ways you can do this. Personally, I do this whenever I run these functions and want to know how long it takes:

```javascript
// Create a startTime variable with the current dateTime
const startTime = Date.now();

// Get my hCaptcha Token and set it as token
let token = await hcaptchaToken("URL HERE", client);

// Create an endTime variable with the current dateTime
const endTime = Date.now();

// Log the amount of time
console.log(`Completed in ${(endTime - startTime) / 1000} seconds`);

// Log the token
console.log(token);
```

This is a very simple way to get the amount of seconds the function took to run.

**Comment by durch2** [comment]
Cool, status as in if it works or not, you could add some CI/CD that prints out time taken as well and adds it to readme too, wonderful project love it

**Comment by aw1875** [comment]
@durch2 I can add the ability to run the functions in a verbose mode if you'd like. I feel like that option would be useful because you would be able to see its status in the process of solving as well.
