### ISSUE TITLE
Some questions about hcaptcha/cloudflare

### ISSUE THREAD

**Issue by andress134** [aw1875/puppeteer-hcaptcha#16]
Hello sir @aw1875 , this post will probably not be considered, as we are dealing with this libraye.
I tested your library, but on some sites it doesn't work the way I would like, and the solve  time is quite long.

So I decided to make some changes (tricks) to the old library, cloudscraper.
Everything seemed to work perfectly, for a few days until cloudflare made a new update and the library stopped working.
I don't know what it updated, and what's wrong with my changes, the library gets sitekey, rayid, and sends data to 2captcha, but h-captcha-response seems invalid.
Here is the lib with my changes i just need some help to undestend what is wrong if is posible. thanks.

// solved, error has from my server

**Comment by aw1875** [comment]
@andress134 Long solve times are usually related to Google Cloud Vision. They are quite fast with rate limiting and since this script is sending 9-18 pictures at a time sometimes it happens very quickly. What sites were you having troubles with so I can take a look at why?
