### ISSUE TITLE
Error: Evaluation failed: TypeError: Cannot read property 'src' of null

### ISSUE THREAD

**Issue by klotein** [aw1875/puppeteer-hcaptcha#2]
const puppeteer = require('puppeteer-extra')
const pluginStealth = require('puppeteer-extra-plugin-stealth')
const vision = require("@google-cloud/vision");

const { hcaptchaToken } = require('puppeteer-hcaptcha');

const client = new vision.ImageAnnotatorClient({
  keyFilename: "test.json",
});

puppeteer.use(pluginStealth());

(async () => {
   
    let token = await hcaptchaToken('https://nooooder.xyz', client);

    // W0_eyJ0eXAiOiJ...
    console.log(token);
})();

**Comment by klotein** [comment]
i tried on windows and linux(debain) i got some Error: Evaluation failed: TypeError: Cannot read property 'src' of null

**Comment by klotein** [comment]
(node:5312) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read property 'src' of null
    at __puppeteer_evaluation_script__:5:6
    at ExecutionContext._evaluateInternal (C:\Users\ops\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:218:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ExecutionContext.evaluate (C:\Users\ops\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:107:16)
    at async hcaptchaToken (C:\Users\ops\node_modules\puppeteer-hcaptcha\hcaptcha.js:249:11)
    at async C:\Users\ops\Desktop\den\server.js:18:17
(Use `node --trace-warnings ...` to show where the warning was created)
(node:5312) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:5312) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by aw1875** [comment]
Thats a cloudflare site. The solver doesn't currently work on cloudflare sites but I will work on fixing this now. Thanks for reporting the issue to me!

**Comment by aw1875** [comment]
Looks like a few things are different for this websites hcaptcha responses. I'm not entirely sure if this is a universal case for all cloudflare hcaptcha responses but I have fixed this issue. Do you mind sending me a few other sites that use cloudflare to test out if this fix is universal for them all?

**Comment by klotein** [comment]
https://cfcaptcha.audiograb.net/hit

**Comment by klotein** [comment]
Probably universal. Because this pages are test pages.

**Comment by aw1875** [comment]
@klotein perfect I'll double check now and push a fix if thats true

**Comment by klotein** [comment]
waiting sir, good luck

**Comment by aw1875** [comment]
Seems like its universal. Going to run a few more quick tests and then a fix will be pushed! Again, thanks for bringing this to my attention.

**Comment by klotein** [comment]
You're welcome.

**Comment by aw1875** [comment]
I was currently in the process of making the image recognition better so that responses were faster so just gotta revert those changes quickly so it'll take a few minutes

**Comment by aw1875** [comment]
New patch is up, enjoy!
