### ISSUE TITLE
Wrong Challenge Type. Retrying.

### ISSUE THREAD

**Issue by yavuz-bektas** [aw1875/puppeteer-hcaptcha#21]
Hello,

I'm trying to use with initial page (demo codes) but I'm receiving below code

`Wrong Challenge Type. Retrying.
Wrong Challenge Type. Retrying.
`

**Comment by aw1875** [comment]
Sorry I was super busy with classes. I have updated the NPM package as well as the repo to dynamically get the version for solving so it shouldn't have any issues anymore. If there are still issues please reopen this issue so I can look into it.
