### ISSUE TITLE
[Bug]: Hcaptcha is meeming with us

### ISSUE THREAD

**Issue by eboujlal** [aw1875/puppeteer-hcaptcha#31]
**Describe the bug**
After 4 hours me and my friend Norbyy looking why car is not equal to car and why train is not equal to train ... then after we run out of logic, he said imagine if that a is not like the other a, we start laughing on it, but it's true. hCaptcha is using Greek letters to replace some letters like e,a,o,c ....

**To Reproduce**

1. You need to add a greek_to_latin function 
2. call it when you extract the word to detect

**Comment by eboujlal** [comment]
by the way it's cyrillic letters

**Comment by aw1875** [comment]
I'm a little confused by this but by the sounds of it you're saying there are issues on websites in another language? Is this correct? If it is would you mind sharing the website you're trying so I can look into it.

**Comment by eboujlal** [comment]
Hey, its discord.com and language of the website is english, we added some codes to your library to its work. Also there is another problem which i will specify in another issue

**Comment by eboujlal** [comment]
Here is my discord if you need some help or screenshare

iiRaven19#7510

**Comment by Oberonskii** [comment]
@eboujlal You got it working on discord? Could you share it?

**Comment by eboujlal** [comment]
> @eboujlal You got it working on discord? Could you share it?

Make a real profile first, don't leech bro

**Comment by Oberonskii** [comment]
You don‘t have to share it, if you dont want ro. I was just asking
