### ISSUE TITLE
Errors Installing 

### ISSUE THREAD

**Issue by Krid86abc** [aw1875/puppeteer-hcaptcha#33]
Hi, i would love to rest your module, but i can't get it work. 
I am using node 10, and receive following error after installing it with npm i:

Error: The Node.js native addon module (tfjs_binding.node) can not be found at path: /home/dbellstaedt/node_modules/@tensorflow/tfjs-node/lib/napi-v7/tfjs_binding.node. 

I use Linux on Chromebook. .
Any Ideas?

Best Regards

**Comment by aw1875** [comment]
This is something that you'll have to check the [TensorFlow Repo](https://github.com/tensorflow/tfjs/issues) about. I'm not entirely sure what their support for chromebook is.

**Comment by Krid86abc** [comment]
I solved it by updated all dependencies, now it works like a charm :)
