### ISSUE TITLE
[Question]: How to work in AWS Lambda?

### ISSUE THREAD

**Issue by pedraohenrique** [aw1875/puppeteer-hcaptcha#35]
Hi there!

I'm trying to run Puppeter Hcaptcha in a AWS Lambda Function, but it can't be done because of Tensorflow library. The original issue [are here](https://github.com/tensorflow/tfjs/issues/2817#issuecomment-594793192).

Can anyone help me?

**Comment by aw1875** [comment]
Based on the issue you referred to it doesn't look like theres anything you can do to run this within an AWS Lambda Function. I personally don't have any experience in this area so I can't be of any help unfortunately so I will leave the issue open in case somebody in the future stumbles upon it and can help.

**Comment by aw1875** [comment]
Seems like there isn't anyone that is able to answer this so I will be closing this issue now due to lack of activity in the thread.
