### ISSUE TITLE
TypeError: browser.userAgent is not a function

### ISSUE THREAD

**Issue by lomso23** [aw1875/puppeteer-hcaptcha#4]
(node:12404) UnhandledPromiseRejectionWarning: TypeError: browser.userAgent is not a function
    at hcaptcha (/test/test/node_modules/puppeteer-hcaptcha/hcaptcha.js:148:35)

Hello, i am getting this error when i use your"https://github.com/aw1875/puppeteer-hcaptcha/blob/master/demos/solve.js"  demo.
Token demo is working good. But this not, thanks.

**Comment by aw1875** [comment]
Are you using the most recent version of the hCaptcha module? The most recent version has made changes to the code so if you're using the demo of the newest version but the code of an older version there would be an issue.

**Comment by lomso23** [comment]
yes, i was tried update not worked, and i got files manuel and im calling like this "const { hcaptcha } = require('./hcaptcha.js);"
but now im getting "wrong response".

**Comment by aw1875** [comment]
Do you mind attaching the hcaptcha.js file? I've never seen this issue so would love to fix this issue if its a problem I can fix

**Comment by lomso23** [comment]
it your hcaptcha.js file on your files.

**Comment by aw1875** [comment]
Please attach the actual file and any relevant screenshots of the errors. As I said that code doesn't exist anymore in the code so I need to figure out why you are getting this problem.

**Comment by lomso23** [comment]
browser.userAgent error solved, i removed old puppeteer-hcaptcha module in node_modules, i installed new version.

PS C:\Users\lomso\Desktop\puppeteer-hcaptcha-master (1)\puppeteer-hcaptcha-master> node .\test.js
Wrong response. Retrying.
Wrong response. Retrying.
Wrong response. Retrying.
Wrong response. Retrying.

**Comment by lomso23** [comment]
im using your demo, just i added my captcha page

**Comment by aw1875** [comment]
> browser.userAgent error solved, i removed old puppeteer-hcaptcha module in node_modules, i installed new version.
> 
> PS C:\Users\lomso\Desktop\puppeteer-hcaptcha-master (1)\puppeteer-hcaptcha-master> node .\test.js
> Wrong response. Retrying.
> Wrong response. Retrying.
> Wrong response. Retrying.
> Wrong response. Retrying.

Ok thats what I expected it was an old version. The wrong answer just means it submitted the wrong answers and it happens sometimes if googles image recognition is not being super accurate. If you dont mind me asking what website you are trying to solve?

**Comment by lomso23** [comment]
https://2captcha.com/demo/hcaptcha and tried on cloudflare captcha page, 

im getting "Wrong response. Retrying." for 2captcha demo page, getting "Error: Evaluation failed: TypeError: Cannot set property 'value' of null" for cf captcha

**Comment by aw1875** [comment]
Thats very odd. I just tested https://2captcha.com/demo/hcaptcha and it worked with no issue so I'm not sure what is the problem. Also which cloudflare site? Want to double check how their requests are being sent.

**Comment by lomso23** [comment]
token response is working, im getting error when i try submit like on your demo like your gif [https://github.com/aw1875/puppeteer-hcaptcha/blob/master/images/demo.gif](url)

**Comment by aw1875** [comment]
Just to be clear, you're using await on your submit function right? Otherwise it will try to submit the form before the function has placed the response in the correct fields.

**Comment by lomso23** [comment]
actually im using this codes

// Require puppeteer extra, puppeteer stealth, google vision
const puppeteer = require('puppeteer-extra')
const pluginStealth = require('puppeteer-extra-plugin-stealth')
const vision = require("@google-cloud/vision");

// Require our hcaptcha method
const { hcaptcha } = require('puppeteer-hcaptcha');

// Instantiate a new Google Vision Client
// This is important so make sure keyFilename points to your credentials
// Our solver method will be using this to speed up the process
const client = new vision.ImageAnnotatorClient({
  keyFilename: "YOUR GOOGLE CREDENTIALS",
});

// Tell puppeteer to use puppeteer stealth
puppeteer.use(pluginStealth());

(async () => {
    // Instantiate a new browser object
    // Ignore errors associated to https
    // Can be headless but for example sake we want to show the browser
    // Set your desired arguments for your puppeteer browser
    const browser = await puppeteer.launch({
        ignoreHTTPSErrors: true,
        headless: false,
        args: [
          `--window-size=600,1000`,
          "--window-position=000,000",
          "--disable-dev-shm-usage",
          "--no-sandbox",
          '--user-data-dir="/tmp/chromium"',
          "--disable-web-security",
          "--disable-features=site-per-process"
        ],
      });

    // Get browser pages
    const [page] = await browser.pages();

    // Send page to your url
    await page.goto('URL OF PAGE WITH CAPTCHA ON IT')

    // Remove the page's default timeout function
    await page.setDefaultNavigationTimeout(0);

    // Call hcaptcha method passing in our page and google vision client
    await hcaptcha(page, client);

    // Your page is ready to submit. Captcha solving should be the last function on your page so we don't have to worry about the response token expiring.
})();

**Comment by lomso23** [comment]
and adding my url

**Comment by aw1875** [comment]
And you're putting in your google credentials correct?

**Comment by lomso23** [comment]
yes sir, because token response working.

**Comment by aw1875** [comment]
I'm not entirely sure what the issue is then unfortunately.

**Comment by aw1875** [comment]
Closing this as I haven't heard anything in a few days
