### ISSUE TITLE
Deprecated packages on installing

### ISSUE THREAD

**Issue by vap999793** [aw1875/puppeteer-hcaptcha#42]
Getting this error while installing

```
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see `https://github.com/request/request/issues/3142`
```

What to do since this is not working or is there any alternate way to resolve this? Please let me know.
Thanks

**Comment by nabil-ak** [comment]
You can still use this package with the outdated dependencies

**Comment by aw1875** [comment]
Yes, the deprecated packages are just warnings. A lot of those dependencies are indirect anyways. I will be closing this issue unless you're having issues do to these warnings.

**Comment by vap999793** [comment]
Hi, 

Thanks for the reply

`npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm ERR! code 1
npm ERR! git dep preparation failed
npm ERR! command C:\Program Files\nodejs\node.exe C:\Users\VISHAL ANAND\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js install --force --cache=C:\Users\VISHAL ANAND\AppData\Local\npm-cache --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-run
npm ERR! > ghost-cursor@1.1.7 prepare
npm ERR! > husky install && yarn lint && yarn build
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! .git can't be found (see https://git.io/Jc3F9)
npm ERR! npm ERR! code 1
npm ERR! npm ERR! path C:\Users\VISHAL ANAND\AppData\Local\npm-cache\_cacache\tmp\git-cloneKtL5qP      
npm ERR! npm ERR! command failed
npm ERR! npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c husky install && yarn lint && yarn build
npm ERR! 
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     C:\Users\VISHAL ANAND\AppData\Local\npm-cache\_logs\2022-02-03T08_52_25_351Z-debug-0.log

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\VISHAL ANAND\AppData\Local\npm-cache\_logs\2022-02-03T08_51_55_111Z-debug-0.log`

Getting deprecated error but it is also not installing the package. I am getting this error everytime.
