### ISSUE TITLE
Moving model loader out of tensor function

### ISSUE THREAD

**Issue by Bogdan1001** [aw1875/puppeteer-hcaptcha#47]
Hey,

I've found that the `model` is loaded each time the `tensor/1` function receives the function, this takes a lot of time. This will be more productive if load it somewhere only one time.

I'm currently fastly have moved it to the `getAnswersTF/2` and called the `tensor/1` with a second parameter like this `tensor(imgUrl, preloadedModel)`. But I think there have a better place for it, any ideas?

**Comment by aw1875** [comment]
Honestly, I'm trying to move away from using tensorflow if possible due to size issues referenced in #41. I'm open to any other suggestions for this type of image recognition.

**Comment by aw1875** [comment]
Haven't heard anything about this for a few months so will be closing this issue. You can open a new issue if there is anything I can fix on my end.
