### ISSUE TITLE
Token received but invalid

### ISSUE THREAD

**Issue by byOsta** [aw1875/puppeteer-hcaptcha#5]
When I try to solve a captcha the token generated is not working. The only thing that I've seen different is that the page that I'm trying to bypass is using ¿HSW? I don't really know if I'm correct or not, but I think that is the only difference.

**Comment by aw1875** [comment]
@byOsta do you mind sharing the page you're trying so I can see if requests are different?

**Comment by byOsta** [comment]
I don't want to disclose publicly the captcha that I'm trying to bypass, so I've sent you and email (The one in your resume on your webpage) with all the info about it.

**Comment by aw1875** [comment]
@byOsta seems like the solver was getting the token before even having to send any real requests so I'm going to push the fix for that in a second. Looks to be working fine now.
![image](https://user-images.githubusercontent.com/36057494/115809088-7872d180-a3b9-11eb-949e-43a552e8d09b.png)

**Comment by aw1875** [comment]
Fix should be pushed, I'm going to close this issue but if you have another problem just open a new issue and I will look into it.
