### ISSUE TITLE
[Question]: How to train it to solve them faster.

### ISSUE THREAD

**Issue by Mako-L** [aw1875/puppeteer-hcaptcha#52]
How to train the model? I'm asking because when the captcha has 2 pages it doesn't pass it.

**Comment by aw1875** [comment]
The models are from TensorFlow. I don't have any models that I have trained myself.

**Comment by Mako-L** [comment]
And with the default model, yours passes the two pages one?

**Comment by aw1875** [comment]
I pass all the images that are sent back in the request. The code is all public so you can take a look through it if you'd like. The only code I don't include is just the test files.
