### ISSUE TITLE
[Question]: Error when requiring @tensorflow/tfjs-node on Mac

### ISSUE THREAD

**Issue by jaspreetbindra** [aw1875/puppeteer-hcaptcha#53]
I am getting error : zsh: illegal hardware instruction  node test.js for even the demo code shared in the documentation. 

Its seem like an issue for M1 chip Macs but any idea how to solve it ?  Seems like tensorflow is not building properly on the machine.

**Comment by aw1875** [comment]
Unfortunately this is more of an issue for their repo.
