### ISSUE TITLE
[Question]: Could you use yolov5

### ISSUE THREAD

**Issue by JokersCat** [aw1875/puppeteer-hcaptcha#54]
I heared yolov5 is faster and you could easily train your own models and stuff I saw captcha solver they average a time around 6 seconds per page or even lower I got times to 4secs for 4 images

**Comment by aw1875** [comment]
Never personally looked into it but I can take a look when I have some free time. Honestly quite busy right now so not sure I'll have the time to get into training any models for this for a while.

**Comment by Revadike** [comment]
> Never personally looked into it but I can take a look when I have some free time. Honestly quite busy right now so not sure I'll have the time to get into training any models for this for a while.

If you need an example:
https://github.com/QIN2DIM/hcaptcha-challenger/tree/main

**Comment by aw1875** [comment]
@wireguard-dev last I looked yolov5 is only for python (unless I missed something). I have an issue template created for suggestions for alternatives that I setup a few weeks ago but at this time there isn't much I can change without doing a massive overhaul.

**Comment by aw1875** [comment]
I'm going to close this issue due to the lack of activity. However, after finals, I may take some time to try and see if I can train my own model and implement it into the system.
