### ISSUE TITLE
[Question]: how do you fix returning undefined?

### ISSUE THREAD

**Issue by ayd0ns** [aw1875/puppeteer-hcaptcha#63]
Captcha returns undefined for me.

**Comment by aw1875** [comment]
Gonna need a little more context to attempt to troubleshoot this

**Comment by ayd0ns** [comment]
instead of returning a captcha key or anything, just returns undefined

**Comment by aw1875** [comment]
Yes I understand that part. What domain are you trying? What does your script look like? File structure? Check out the bug report template for some ideas of what might help me out. Its possible that the model is just having issue with the images but I need to know exactly what to look for here.

**Comment by roralsorom** [comment]
hello @aw1875 this is my code 
i dont see anything wrong
**_// Require our hcaptchaToken method
const { hcaptchaToken } = require("puppeteer-hcaptcha");

(async () => {
    // Create Start Time
    const startTime = Date.now();

    // Call hcaptchaToken method passing in your url
    let token = await hcaptchaToken("https://shimuldn.github.io/hCaptchaSolverApi/demo_data/demo_sites/2/");

    // Get End Time
    const endTime = Date.now();

    // Log timed result to console
    console.log(`Completed in ${(endTime - startTime) / 1000} seconds`);

    // P0_eyJ0eXAiOiJ...
    console.log(token);
})();_**

**Comment by aw1875** [comment]
@roralsorom what issue are you having?

**Comment by aw1875** [comment]
I walked through the code step by step for the given url and got an appropriate response 
![image](https://user-images.githubusercontent.com/4970015/182291804-3d55e162-6bc1-4e65-8940-1293ee81acfb.png)

So if it's some other issue please let me know so I can look into it.

**Comment by aw1875** [comment]
I'm going to close this now as I haven't heard anything in over a week. If you still require help you can comment on this again or open a new issue.
