### ISSUE TITLE
I cant install the package

### ISSUE THREAD

**Issue by 1iPluto** [aw1875/puppeteer-hcaptcha#67]
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\Administrator\Desktop\Discord-Token-Generator-main\node_modules\@mapbox\node-pre-gyp\lib\util\compile.js:89:23)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1092:16)
npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
npm ERR! node-pre-gyp ERR! System Windows_NT 10.0.19043
npm ERR! node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Administrator\\Desktop\\Discord-Token-Generator-main\\node_modules\\@mapbox\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd C:\Users\Administrator\Desktop\Discord-Token-Generator-main\node_modules\@tensorflow\tfjs-node
npm ERR! node-pre-gyp ERR! node -v v16.16.0
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.9
npm ERR! node-pre-gyp ERR! not ok
npm ERR! * Downloading libtensorflow
npm ERR!
npm ERR! * Building TensorFlow Node.js bindings

**Comment by aw1875** [comment]
Make sure you have Visual Studio C++ build tools

**Comment by aw1875** [comment]
Regardless, this is more of a tensorflow issue so I'll be closing this.
