### ISSUE TITLE
[Question]: Continuously getting error "Wrong Response, Retrying"

### ISSUE THREAD

**Issue by Utsav-2345** [aw1875/puppeteer-hcaptcha#68]
```
const puppeteer = require("puppeteer-extra");
const pluginStealth = require("puppeteer-extra-plugin-stealth");

const { hcaptcha } = require("puppeteer-hcaptcha");

puppeteer.use(pluginStealth());

(async () => {
    const browser = await puppeteer.launch({
        ignoreHTTPSErrors: true,
        headless: false,
        args: [
            `--window-size=600,1000`,
            "--window-position=000,000",
            "--disable-dev-shm-usage",
            "--no-sandbox",
            '--user-data-dir="/tmp/chromium"',
            "--disable-web-security",
            "--disable-features=site-per-process",
        ],
    });

    const [page] = await browser.pages();

    await page.goto("https://democaptcha.com/demo-form-eng/hcaptcha.html");

    await page.setDefaultNavigationTimeout(0);

     await hcaptcha(page);
        

})();

```

I tried to test this project on a simple hcaptcha demo website but i keep getting error "Wrong Response, Retrying"

**Comment by aw1875** [comment]
The image recognition struggles quite a bit with the blurred/pixelated images that hCaptcha is using currently and I haven't really found a solution for that. It does work still but it takes quite a few attempts sometimes. You can try pulling down the [typescript branch](https://github.com/aw1875/puppeteer-hcaptcha/tree/typescript) and running the code that way as there is an optional parameter for debugging that will log out each step and what it fails on. If you want to try this out an example code block for the token only version would look like this:

```typescript
import hCaptcha from './lib/hcaptcha.js';

(async () => {
    const token = await hCaptcha.tokenOnly("https://democaptcha.com/demo-form-eng/hcaptcha.html", true);
    console.log(token)
})();
```

You should see something like this:

![2022-08-17_105512](https://user-images.githubusercontent.com/4970015/185172246-50932771-33c0-4922-b2c6-0d50dc859a01.png)

**Comment by aw1875** [comment]
If you go this route, it should be a little more clear what the actual issue is. I've been noticing that during most tests the ML model is unable to classify the image so its returning blank answers so if you get an error message like "Failed to get answers" thats why. For the same reason, sometimes it is able to classify them but not as accurately as we'd like so it will fail when checking the answers as they won't all be right.

**Comment by aw1875** [comment]
I'm going to close this issue as I haven't heard anything in a few days. If you have any other questions you may open a new issue.
