### ISSUE TITLE
[Question]:invalid, unusable

### ISSUE THREAD

**Issue by chickmy** [aw1875/puppeteer-hcaptcha#70]
```
const { hcaptchaToken } = require("puppeteer-hcaptcha");

(async () => {
    // Create Start Time
    const startTime = Date.now();

    // Call hcaptchaToken method passing in your url
    let token = await hcaptchaToken("https://2captcha.com/demo/hcaptcha");

    // Get End Time
    const endTime = Date.now();

    // Log timed result to console
    console.log(`Completed in ${(endTime - startTime) / 1000} seconds`);

    // P0_eyJ0eXAiOiJ...
    console.log(token);
})();
```
Prompt error:
![image](https://user-images.githubusercontent.com/42132304/194046818-80202991-e567-4fb2-83ab-68ebed68ff3c.png)

**Comment by aw1875** [comment]
That just means it got the images wrong. hCaptcha has started to change so either their images are blurry/pixelated now or the tasks are much more in-depth and the image recognition being used struggles with it sometimes. Unfortunately there isn't much I can do currently unless there is a better image model to use.
