### ISSUE TITLE
Make Google Vision optional

### ISSUE THREAD

**Issue by Jytesh** [aw1875/puppeteer-hcaptcha#8]
If google vision just speeds up the solving process, is it possible to make it guess random values and make the vision client completely optional?

**Comment by aw1875** [comment]
@Jytesh it is possible but there are other modules that already do that. [Jimmy Laurent's Module](https://github.com/JimmyLaurent/hcaptcha-solver/) does exactly that. The whole process behind using Google Vision here is that the solution time is exponentially faster. You can sign up for Google Vision for free with a $300 credit and it is definitely worth the setup.

**Comment by Jytesh** [comment]
Jimmy Laurent's module is not updated and doesn't work :( thats the issue for me

**Comment by aw1875** [comment]
If you're comfortable with node you can fairly easily tweak my code to randomly guess answers instead of using but like I said that slows down the solution a ton

**Comment by Jytesh** [comment]
Aight thanks, am doing that, how much faster is it when using google vision?

**Comment by aw1875** [comment]
Average solving time is usually 2-12 seconds with google vision and its 45+ without

**Comment by Jytesh** [comment]
Aight thanks :), would you accept a PR that just uses random t/f instead of google vision incase its not provided instead of returning undefined?

**Comment by aw1875** [comment]
@Jytesh I'd be open to having that as an option if a user sets it to run that way. Easiest way might be to add config settings to each function.

**Comment by Jytesh** [comment]
aight, thoughts on leaving request as well?

**Comment by aw1875** [comment]
by all means. I want to work on fixing HSJ requests first as thats my top priority so I'm trying to do that around my work schedule
